# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

# Time/Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, .65)
    font_size = 22
    font_family = SF Pro Display Bold
    position = 0, 420
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(255, 255, 255, .65)
    font_size = 90
    font_family = SF Pro Display Bold
    position = 0, 350
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = "Fingerprint Ready"
    fingerprint:present_message = "Scanning"
    fingerprint:retry_delay = 100
}

# PASSWORD-TEXT
label {
    monitor =
    text = Password:
    color = rgba(255, 255, 255, .55)
    font_size = 17
    font_family = SF Pro Display Bold 
    position = -90, -70
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 350, 40
    rounding = 0
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(86, 90, 90, 1)
    inner_color = rgba(40, 40, 40, 1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 30, -125
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] mpc current
    color = rgba(255, 255, 255, 0.55)
    font_size = 17
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 0, 30
    halign = center
    valign = bottom
}
