preload = ~/Media/Image/Wallpapers/calder-moore-factorycomped.jpg 
preload = ~/Media/Image/Wallpapers/calder-moore-scifi-elevator.jpg 


#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = eDP-1,~/Media/Image/Wallpapers/calder-moore-factorycomped.jpg 
#wallpaper = DP-9,~/Media/Image/Wallpapers/calder-moore-scifi-elevator.jpg 

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
